import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MyNav from './../components/MyNav/MyNav';
import Footer from "@/components/Footer/footer";
import { Flip, Slide, ToastContainer } from "react-toastify";
import HeaderPage from "@/components/sections/Home/Header";
import ModelSearch from "@/components/MyNav/ModelSearch";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}
        `}
      >
        <HeaderPage />
        <MyNav />
        <div className="w-full h-[100px]"></div>
        <div className=" min-h-[850px] pb-24">
          {children}
        </div>
        <ToastContainer
          position="bottom-right"
          autoClose={1000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick={false}
          rtl={false}
          pauseOnFocusLoss={false}
          draggable
          pauseOnHover
          theme="light"
          transition={Slide}
        />
        <ModelSearch />
        <Footer />
      </body>
    </html>
  );
}
